"""Level 6 — Incremental processing pipeline.

Simulates a warehouse that receives one file per day
(orders_2026_08_01.csv, orders_2026_08_02.csv, ...) and must:

    * detect new files (manifest of already-processed files)
    * process only new data
    * deduplicate records (an order may reappear in a later file as an update)
    * update the analytical orders table
    * produce daily aggregates
    * handle late-arriving records (an old order arriving in a new file)

State:
    data/incremental/            incoming daily batches (generated by --init)
    gold.incremental_orders      merged, deduplicated orders
    gold.incremental_daily       daily aggregates
    data/manifest.json           files already consumed (name -> sha256)

Usage:
    python src/incremental.py --init            # create the daily batches
    python src/incremental.py --run             # consume new files (idempotent)
    python src/incremental.py --init --run      # both
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import time
from datetime import date, datetime, timedelta
from pathlib import Path

from config import load_config
from db import connect, copy_csv, fmt_dur

ORDER_COLUMNS = ["order_id", "customer_id", "order_date", "updated_at", "status",
                 "channel", "currency", "shipping_country", "total_amount", "n_items"]

STAGE_DDL = """
    CREATE TABLE IF NOT EXISTS inc_stage (
        order_id BIGINT, customer_id BIGINT, order_date DATE, updated_at TIMESTAMP,
        status TEXT, channel TEXT, currency TEXT, shipping_country TEXT,
        total_amount DOUBLE PRECISION, n_items INT
    ) DISTRIBUTED BY (order_id)
"""

TARGET_DDL = """
    CREATE TABLE IF NOT EXISTS gold.incremental_orders (
        order_id BIGINT, customer_id BIGINT, order_date DATE, updated_at TIMESTAMP,
        status TEXT, channel TEXT, currency TEXT, shipping_country TEXT,
        total_amount DOUBLE PRECISION, n_items INT
    ) DISTRIBUTED BY (order_id)
"""

DAILY_DDL = """
    CREATE TABLE IF NOT EXISTS gold.incremental_daily (
        order_date DATE, orders BIGINT, customers BIGINT,
        revenue DOUBLE PRECISION, valid_revenue DOUBLE PRECISION
    ) DISTRIBUTED BY (order_date)
"""


def make_batch(out_dir: Path, day: str, day_idx: int, n: int, seed: int,
               overlap_from: str | None = None, late: str | None = None) -> None:
    """Write a single day's orders CSV.

    day_idx: 0-based index of the day; each day owns a disjoint order_id
             range [day_idx*n+1, (day_idx+1)*n] so batches don't collide.
    overlap_from: some order_ids from that earlier day's file are re-emitted
                  as 'updated' rows (later updated_at) — the pipeline must
                  deduplicate them.
    late: one order with this order_date (earlier than `day`) is included,
          simulating a late-arriving record.
    """
    rng = random.Random(seed)
    lo, hi = day_idx * n + 1, (day_idx + 1) * n
    rows = []
    for i in range(lo, hi + 1):
        rows.append((
            i,
            1 + rng.randrange(20000),
            day,
            f"{day} {9 + rng.randrange(8):02d}:00:00",
            "completed", "web", "USD", "US",
            round(rng.random() * 400 + 20, 2),
            1 + rng.randrange(4),
        ))

    if overlap_from:
        prev = out_dir / f"orders_{overlap_from}.csv"
        with open(prev, "r", newline="", encoding="utf-8") as fh:
            for r in list(csv.reader(fh))[1:]:
                if rng.random() < 0.01:             # ~1% of earlier orders updated
                    upd = datetime.strptime(r[3], "%Y-%m-%d %H:%M:%S") + timedelta(days=1)
                    rows.append((int(r[0]), int(r[1]), r[2], upd.strftime("%Y-%m-%d %H:%M:%S"),
                                 "completed", r[5], r[6], r[7], round(float(r[8]) * 1.1, 2),
                                 int(r[9])))

    if late:
        rows.append((
            900000000 + rng.randrange(100000),
            1 + rng.randrange(20000),
            late,
            f"{day} 23:00:00",
            "completed", "mobile_app", "USD", "CA",
            round(rng.random() * 200 + 20, 2),
            2,
        ))

    out = out_dir / f"orders_{day}.csv"
    with open(out, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(ORDER_COLUMNS)
        w.writerows(rows)
    print(f"    wrote {out.name}  rows={len(rows):,}")


def init_batches(cfg) -> None:
    inc = Path(cfg.data["incremental"])
    print("=== Level 6: initializing daily batches ===\n")
    days = ["2026-08-01", "2026-08-02", "2026-08-03", "2026-08-04"]
    for i, d in enumerate(days):
        make_batch(inc, d, day_idx=i, n=80_000, seed=100 + i,
                   overlap_from=days[i - 1] if i > 0 else None,
                   late="2026-07-31" if i == 2 else None)
    print("\nBatches ready. Run `python src/incremental.py --run` to consume them.")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_manifest(cfg) -> dict:
    mf = Path(cfg.data["manifest"])
    if mf.exists():
        return json.loads(mf.read_text(encoding="utf-8"))
    return {}


def save_manifest(cfg, manifest: dict) -> None:
    Path(cfg.data["manifest"]).write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def q1(con, sql: str):
    with con.cursor() as cur:
        cur.execute(sql)
        return cur.fetchone()[0]


def run_pipeline(cfg) -> None:
    con = connect(cfg)
    inc = Path(cfg.data["incremental"])
    gold_dir = Path(cfg.data["gold"])
    gold_dir.mkdir(parents=True, exist_ok=True)

    manifest = load_manifest(cfg)
    new_files = sorted(inc.glob("orders_*.csv"))
    new_files = [f for f in new_files if manifest.get(f.name) != sha256_file(f)]

    if not new_files:
        print("No new files to process (manifest is up to date).")
        return

    print("=== Level 6: incremental pipeline ===\n")
    print(f"New files detected: {[f.name for f in new_files]}")

    with con.cursor() as cur:
        cur.execute("CREATE SCHEMA IF NOT EXISTS gold")
        cur.execute(STAGE_DDL)
        cur.execute("TRUNCATE inc_stage")
        cur.execute(TARGET_DDL)
        cur.execute(DAILY_DDL)

    # 1) load the new files into staging
    st = time.perf_counter()
    new_rows = 0
    for f in new_files:
        n = copy_csv(con, "inc_stage", ORDER_COLUMNS, f)
        new_rows += n
        print(f"  staged {f.name:<24} rows={n:>8,}")
    with con.cursor() as cur:
        cur.execute("ANALYZE inc_stage")

    # 2) merge: new + existing, keep the latest updated_at per order_id
    n_before = q1(con, "SELECT count(*) FROM gold.incremental_orders")
    st = time.perf_counter()
    with con.cursor() as cur:
        cur.execute("""
            CREATE TEMP TABLE inc_merge AS
            WITH all_rows AS (
                SELECT * FROM inc_stage
                UNION ALL
                SELECT * FROM gold.incremental_orders
            )
            SELECT order_id, customer_id, order_date, updated_at, status, channel,
                   currency, shipping_country, total_amount, n_items
            FROM (
                SELECT *, row_number() OVER (PARTITION BY order_id
                                             ORDER BY updated_at DESC) AS rn
                FROM all_rows
            ) t
            WHERE rn = 1
            DISTRIBUTED BY (order_id)
        """)
        cur.execute("TRUNCATE gold.incremental_orders")
        cur.execute("INSERT INTO gold.incremental_orders SELECT * FROM inc_merge")
        cur.execute("DROP TABLE IF EXISTS inc_merge")
        cur.execute("ANALYZE gold.incremental_orders")
    n_after = q1(con, "SELECT count(*) FROM gold.incremental_orders")
    dupes = n_before + new_rows - n_after
    print(f"  merged {n_before:,} -> {n_after:,} rows "
          f"(dropped {dupes:,} duplicate/updated order_ids)  "
          f"[{fmt_dur(time.perf_counter() - st)}]")

    # 3) daily aggregates — recompute for all days touched (incl. late arrivals)
    st = time.perf_counter()
    with con.cursor() as cur:
        cur.execute("TRUNCATE gold.incremental_daily")
        cur.execute("""
            INSERT INTO gold.incremental_daily
            SELECT order_date,
                   COUNT(*) AS orders,
                   COUNT(DISTINCT customer_id) AS customers,
                   SUM(total_amount) AS revenue,
                   SUM(CASE WHEN status != 'cancelled' THEN total_amount ELSE 0 END)
                       AS valid_revenue
            FROM gold.incremental_orders
            GROUP BY 1 ORDER BY 1
        """)
    days = q1(con, "SELECT count(*) FROM gold.incremental_daily")
    print(f"  recomputed daily aggregates: {days} days  [{fmt_dur(time.perf_counter() - st)}]")

    # 4) update the manifest
    for f in new_files:
        manifest[f.name] = sha256_file(f)
    save_manifest(cfg, manifest)
    print(f"  manifest updated -> {Path(cfg.data['manifest'])}")

    # 5) show the daily table (late arrival should be visible on 07-31)
    print("\n  daily aggregates:")
    with con.cursor() as cur:
        cur.execute("SELECT order_date, orders, customers, revenue "
                    "FROM gold.incremental_daily ORDER BY order_date")
        for r in cur.fetchall():
            print(f"    {r[0]}  orders={r[1]:>7,}  customers={r[2]:>7,}  "
                  f"revenue={float(r[3]):>13,.2f}")

        cur.execute("""
            SELECT order_id, order_date, updated_at, total_amount
            FROM gold.incremental_orders
            WHERE order_date < DATE '2026-08-01'
        """)
        late = cur.fetchall()
    if late:
        print(f"\n  late-arriving orders (order_date before the batch range): {len(late)}")
        for r in late[:3]:
            print(f"    order {r[0]} dated {r[1]} (arrived, updated_at {r[2]}) "
                  f"amount={r[3]}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Incremental batch pipeline")
    ap.add_argument("--init", action="store_true", help="create the daily batch files")
    ap.add_argument("--run", action="store_true", help="consume new batch files")
    args = ap.parse_args()

    cfg = load_config()
    if args.init:
        init_batches(cfg)
    if args.run:
        run_pipeline(cfg)
    if not args.init and not args.run:
        ap.print_help()


if __name__ == "__main__":
    main()
